export const PLAN_FEATURES = Object.freeze({
  JOB_LISTING: 'JOB_LISTING',
  JOB_LISTING_APPLICATION: 'JOB_LISTING_APPLICATION',
  JOB_LISTING_WRITE: 'JOB_LISTING_WRITE',
  MANAGE_APPLICANT_WORKFLOW: 'MANAGE_APPLICANT_WORKFLOW',
  POST_1_JOB_LISTING: 'POST_1_JOB_LISTING',
  POST_3_JOB_LISTING: 'POST_3_JOB_LISTING',
  POST_15_JOB_LISTING: 'POST_15_JOB_LISTING',
  ONE_FEATURED_JOB_LISTING: '1_FEATURED_JOB_LISTING',
  UNLIMITED_FEATURED_JOB_LISTING: 'UNLIMITED_FEATURED_JOB_LISTING'
})