/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationSwitcherRouteImport } from './routes/organization-switcher'
import { Route as jobSeekerLayoutRouteImport } from './routes/(job-seeker)/_layout'
import { Route as employerLayoutRouteImport } from './routes/(employer)/_layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as jobSeekerLayoutIndexRouteImport } from './routes/(job-seeker)/_layout.index'
import { Route as jobSeekerLayoutPersonalInfoRouteImport } from './routes/(job-seeker)/_layout.personal-info'
import { Route as jobSeekerLayoutAiSearchRouteImport } from './routes/(job-seeker)/_layout.ai-search'
import { Route as authLayoutSignInRouteImport } from './routes/(auth)/_layout.sign-in'
import { Route as employerLayoutEmployerIndexRouteImport } from './routes/(employer)/_layout.employer.index'
import { Route as employerLayoutEmployerPricingRouteImport } from './routes/(employer)/_layout.employer.pricing'
import { Route as employerLayoutEmployerJobListingsNewRouteImport } from './routes/(employer)/_layout.employer.job-listings.new'
import { Route as employerLayoutEmployerJobListingsJobListingIDIndexRouteImport } from './routes/(employer)/_layout.employer.job-listings.$jobListingID.index'
import { Route as employerLayoutEmployerJobListingsJobListingIDEditRouteImport } from './routes/(employer)/_layout.employer.job-listings.$jobListingID.edit'

const OrganizationSwitcherRoute = OrganizationSwitcherRouteImport.update({
  id: '/organization-switcher',
  path: '/organization-switcher',
  getParentRoute: () => rootRouteImport,
} as any)
const jobSeekerLayoutRoute = jobSeekerLayoutRouteImport.update({
  id: '/(job-seeker)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const employerLayoutRoute = employerLayoutRouteImport.update({
  id: '/(employer)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const jobSeekerLayoutIndexRoute = jobSeekerLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => jobSeekerLayoutRoute,
} as any)
const jobSeekerLayoutPersonalInfoRoute =
  jobSeekerLayoutPersonalInfoRouteImport.update({
    id: '/personal-info',
    path: '/personal-info',
    getParentRoute: () => jobSeekerLayoutRoute,
  } as any)
const jobSeekerLayoutAiSearchRoute = jobSeekerLayoutAiSearchRouteImport.update({
  id: '/ai-search',
  path: '/ai-search',
  getParentRoute: () => jobSeekerLayoutRoute,
} as any)
const authLayoutSignInRoute = authLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)
const employerLayoutEmployerIndexRoute =
  employerLayoutEmployerIndexRouteImport.update({
    id: '/employer/',
    path: '/employer/',
    getParentRoute: () => employerLayoutRoute,
  } as any)
const employerLayoutEmployerPricingRoute =
  employerLayoutEmployerPricingRouteImport.update({
    id: '/employer/pricing',
    path: '/employer/pricing',
    getParentRoute: () => employerLayoutRoute,
  } as any)
const employerLayoutEmployerJobListingsNewRoute =
  employerLayoutEmployerJobListingsNewRouteImport.update({
    id: '/employer/job-listings/new',
    path: '/employer/job-listings/new',
    getParentRoute: () => employerLayoutRoute,
  } as any)
const employerLayoutEmployerJobListingsJobListingIDIndexRoute =
  employerLayoutEmployerJobListingsJobListingIDIndexRouteImport.update({
    id: '/employer/job-listings/$jobListingID/',
    path: '/employer/job-listings/$jobListingID/',
    getParentRoute: () => employerLayoutRoute,
  } as any)
const employerLayoutEmployerJobListingsJobListingIDEditRoute =
  employerLayoutEmployerJobListingsJobListingIDEditRouteImport.update({
    id: '/employer/job-listings/$jobListingID/edit',
    path: '/employer/job-listings/$jobListingID/edit',
    getParentRoute: () => employerLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/organization-switcher': typeof OrganizationSwitcherRoute
  '/sign-in': typeof authLayoutSignInRoute
  '/ai-search': typeof jobSeekerLayoutAiSearchRoute
  '/personal-info': typeof jobSeekerLayoutPersonalInfoRoute
  '/': typeof jobSeekerLayoutIndexRoute
  '/employer/pricing': typeof employerLayoutEmployerPricingRoute
  '/employer/': typeof employerLayoutEmployerIndexRoute
  '/employer/job-listings/new': typeof employerLayoutEmployerJobListingsNewRoute
  '/employer/job-listings/$jobListingID/edit': typeof employerLayoutEmployerJobListingsJobListingIDEditRoute
  '/employer/job-listings/$jobListingID/': typeof employerLayoutEmployerJobListingsJobListingIDIndexRoute
}
export interface FileRoutesByTo {
  '/organization-switcher': typeof OrganizationSwitcherRoute
  '/sign-in': typeof authLayoutSignInRoute
  '/ai-search': typeof jobSeekerLayoutAiSearchRoute
  '/personal-info': typeof jobSeekerLayoutPersonalInfoRoute
  '/': typeof jobSeekerLayoutIndexRoute
  '/employer/pricing': typeof employerLayoutEmployerPricingRoute
  '/employer': typeof employerLayoutEmployerIndexRoute
  '/employer/job-listings/new': typeof employerLayoutEmployerJobListingsNewRoute
  '/employer/job-listings/$jobListingID/edit': typeof employerLayoutEmployerJobListingsJobListingIDEditRoute
  '/employer/job-listings/$jobListingID': typeof employerLayoutEmployerJobListingsJobListingIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/organization-switcher': typeof OrganizationSwitcherRoute
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(employer)/_layout': typeof employerLayoutRouteWithChildren
  '/(job-seeker)/_layout': typeof jobSeekerLayoutRouteWithChildren
  '/(auth)/_layout/sign-in': typeof authLayoutSignInRoute
  '/(job-seeker)/_layout/ai-search': typeof jobSeekerLayoutAiSearchRoute
  '/(job-seeker)/_layout/personal-info': typeof jobSeekerLayoutPersonalInfoRoute
  '/(job-seeker)/_layout/': typeof jobSeekerLayoutIndexRoute
  '/(employer)/_layout/employer/pricing': typeof employerLayoutEmployerPricingRoute
  '/(employer)/_layout/employer/': typeof employerLayoutEmployerIndexRoute
  '/(employer)/_layout/employer/job-listings/new': typeof employerLayoutEmployerJobListingsNewRoute
  '/(employer)/_layout/employer/job-listings/$jobListingID/edit': typeof employerLayoutEmployerJobListingsJobListingIDEditRoute
  '/(employer)/_layout/employer/job-listings/$jobListingID/': typeof employerLayoutEmployerJobListingsJobListingIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/organization-switcher'
    | '/sign-in'
    | '/ai-search'
    | '/personal-info'
    | '/'
    | '/employer/pricing'
    | '/employer/'
    | '/employer/job-listings/new'
    | '/employer/job-listings/$jobListingID/edit'
    | '/employer/job-listings/$jobListingID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/organization-switcher'
    | '/sign-in'
    | '/ai-search'
    | '/personal-info'
    | '/'
    | '/employer/pricing'
    | '/employer'
    | '/employer/job-listings/new'
    | '/employer/job-listings/$jobListingID/edit'
    | '/employer/job-listings/$jobListingID'
  id:
    | '__root__'
    | '/organization-switcher'
    | '/(auth)/_layout'
    | '/(employer)/_layout'
    | '/(job-seeker)/_layout'
    | '/(auth)/_layout/sign-in'
    | '/(job-seeker)/_layout/ai-search'
    | '/(job-seeker)/_layout/personal-info'
    | '/(job-seeker)/_layout/'
    | '/(employer)/_layout/employer/pricing'
    | '/(employer)/_layout/employer/'
    | '/(employer)/_layout/employer/job-listings/new'
    | '/(employer)/_layout/employer/job-listings/$jobListingID/edit'
    | '/(employer)/_layout/employer/job-listings/$jobListingID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OrganizationSwitcherRoute: typeof OrganizationSwitcherRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  employerLayoutRoute: typeof employerLayoutRouteWithChildren
  jobSeekerLayoutRoute: typeof jobSeekerLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organization-switcher': {
      id: '/organization-switcher'
      path: '/organization-switcher'
      fullPath: '/organization-switcher'
      preLoaderRoute: typeof OrganizationSwitcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(job-seeker)/_layout': {
      id: '/(job-seeker)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof jobSeekerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(employer)/_layout': {
      id: '/(employer)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof employerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(job-seeker)/_layout/': {
      id: '/(job-seeker)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof jobSeekerLayoutIndexRouteImport
      parentRoute: typeof jobSeekerLayoutRoute
    }
    '/(job-seeker)/_layout/personal-info': {
      id: '/(job-seeker)/_layout/personal-info'
      path: '/personal-info'
      fullPath: '/personal-info'
      preLoaderRoute: typeof jobSeekerLayoutPersonalInfoRouteImport
      parentRoute: typeof jobSeekerLayoutRoute
    }
    '/(job-seeker)/_layout/ai-search': {
      id: '/(job-seeker)/_layout/ai-search'
      path: '/ai-search'
      fullPath: '/ai-search'
      preLoaderRoute: typeof jobSeekerLayoutAiSearchRouteImport
      parentRoute: typeof jobSeekerLayoutRoute
    }
    '/(auth)/_layout/sign-in': {
      id: '/(auth)/_layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authLayoutSignInRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(employer)/_layout/employer/': {
      id: '/(employer)/_layout/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof employerLayoutEmployerIndexRouteImport
      parentRoute: typeof employerLayoutRoute
    }
    '/(employer)/_layout/employer/pricing': {
      id: '/(employer)/_layout/employer/pricing'
      path: '/employer/pricing'
      fullPath: '/employer/pricing'
      preLoaderRoute: typeof employerLayoutEmployerPricingRouteImport
      parentRoute: typeof employerLayoutRoute
    }
    '/(employer)/_layout/employer/job-listings/new': {
      id: '/(employer)/_layout/employer/job-listings/new'
      path: '/employer/job-listings/new'
      fullPath: '/employer/job-listings/new'
      preLoaderRoute: typeof employerLayoutEmployerJobListingsNewRouteImport
      parentRoute: typeof employerLayoutRoute
    }
    '/(employer)/_layout/employer/job-listings/$jobListingID/': {
      id: '/(employer)/_layout/employer/job-listings/$jobListingID/'
      path: '/employer/job-listings/$jobListingID'
      fullPath: '/employer/job-listings/$jobListingID/'
      preLoaderRoute: typeof employerLayoutEmployerJobListingsJobListingIDIndexRouteImport
      parentRoute: typeof employerLayoutRoute
    }
    '/(employer)/_layout/employer/job-listings/$jobListingID/edit': {
      id: '/(employer)/_layout/employer/job-listings/$jobListingID/edit'
      path: '/employer/job-listings/$jobListingID/edit'
      fullPath: '/employer/job-listings/$jobListingID/edit'
      preLoaderRoute: typeof employerLayoutEmployerJobListingsJobListingIDEditRouteImport
      parentRoute: typeof employerLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authLayoutSignInRoute: typeof authLayoutSignInRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutSignInRoute: authLayoutSignInRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface employerLayoutRouteChildren {
  employerLayoutEmployerPricingRoute: typeof employerLayoutEmployerPricingRoute
  employerLayoutEmployerIndexRoute: typeof employerLayoutEmployerIndexRoute
  employerLayoutEmployerJobListingsNewRoute: typeof employerLayoutEmployerJobListingsNewRoute
  employerLayoutEmployerJobListingsJobListingIDEditRoute: typeof employerLayoutEmployerJobListingsJobListingIDEditRoute
  employerLayoutEmployerJobListingsJobListingIDIndexRoute: typeof employerLayoutEmployerJobListingsJobListingIDIndexRoute
}

const employerLayoutRouteChildren: employerLayoutRouteChildren = {
  employerLayoutEmployerPricingRoute: employerLayoutEmployerPricingRoute,
  employerLayoutEmployerIndexRoute: employerLayoutEmployerIndexRoute,
  employerLayoutEmployerJobListingsNewRoute:
    employerLayoutEmployerJobListingsNewRoute,
  employerLayoutEmployerJobListingsJobListingIDEditRoute:
    employerLayoutEmployerJobListingsJobListingIDEditRoute,
  employerLayoutEmployerJobListingsJobListingIDIndexRoute:
    employerLayoutEmployerJobListingsJobListingIDIndexRoute,
}

const employerLayoutRouteWithChildren = employerLayoutRoute._addFileChildren(
  employerLayoutRouteChildren,
)

interface jobSeekerLayoutRouteChildren {
  jobSeekerLayoutAiSearchRoute: typeof jobSeekerLayoutAiSearchRoute
  jobSeekerLayoutPersonalInfoRoute: typeof jobSeekerLayoutPersonalInfoRoute
  jobSeekerLayoutIndexRoute: typeof jobSeekerLayoutIndexRoute
}

const jobSeekerLayoutRouteChildren: jobSeekerLayoutRouteChildren = {
  jobSeekerLayoutAiSearchRoute: jobSeekerLayoutAiSearchRoute,
  jobSeekerLayoutPersonalInfoRoute: jobSeekerLayoutPersonalInfoRoute,
  jobSeekerLayoutIndexRoute: jobSeekerLayoutIndexRoute,
}

const jobSeekerLayoutRouteWithChildren = jobSeekerLayoutRoute._addFileChildren(
  jobSeekerLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  OrganizationSwitcherRoute: OrganizationSwitcherRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  employerLayoutRoute: employerLayoutRouteWithChildren,
  jobSeekerLayoutRoute: jobSeekerLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
